# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9552f7f0a27287c08634cde853f9a029c53dc832435f7c0d258863d3da7059cf3be42b19829de1582152b363517b515583fa8b737668eb36413b63b7d786e7ef

test:
  secret_key_base: 272c0fe8f921738d774db6cd61d511ff897b98976fa7481be266607308d60c7beafcc0b77aefe0bd9892bc7f6df778561c0e96ab229f0daa1cee56a5da9477b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
